name: Pipeline for Main branch
on:
  push:
    branches: [ "main"]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.3
      - name: Setup Java 17 JDK
        uses: actions/setup-java@v1.4.4
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Gradle Build Action
        uses: gradle/gradle-build-action@v2.5.1
        with:
          arguments: build
